Name: CVE-2011-4137
Status: Candidate
URL: http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2011-4137
Phase: Assigned (20111019)
Category: 
Reference: MLIST:[oss-security] 20110911 CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws
Reference: URL:http://openwall.com/lists/oss-security/2011/09/11/1
Reference: MLIST:[oss-security] 20110913 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws
Reference: URL:http://openwall.com/lists/oss-security/2011/09/13/2
Reference: MLIST:[oss-security] 20110916 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws
Reference: URL:http://openwall.com/lists/oss-security/2011/09/15/5
Reference: CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=737366
Reference: CONFIRM:https://www.djangoproject.com/weblog/2011/sep/09/
Reference: CONFIRM:https://www.djangoproject.com/weblog/2011/sep/10/127/
Reference: DEBIAN:DSA-2332
Reference: URL:http://www.debian.org/security/2011/dsa-2332
Reference: SUSE:openSUSE-SU-2012:0653
Reference: URL:https://hermes.opensuse.org/messages/14700881
Reference: SECUNIA:46614
Reference: URL:http://secunia.com/advisories/46614

The verify_exists functionality in the URLField implementation in
Django before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries
that attempt access to an arbitrary URL with no timeout, which allows
remote attackers to cause a denial of service (resource consumption)
via a URL associated with (1) a slow response, (2) a completed TCP
connection with no application data sent, or (3) a large amount of
application data, a related issue to CVE-2011-1521.


Current Votes:
None (candidate not yet proposed)


