Name: CVE-2010-3493
Status: Candidate
URL: http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-3493
Phase: Assigned (20100924)
Category: 
Reference: MLIST:[oss-security] 20100909 CVE Request -- Python -- accept() implementation in async core is broken => more subcases
Reference: URL:http://www.openwall.com/lists/oss-security/2010/09/09/6
Reference: MLIST:[oss-security] 20100910 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases
Reference: URL:http://www.openwall.com/lists/oss-security/2010/09/11/2
Reference: MLIST:[oss-security] 20100922 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases
Reference: URL:http://www.openwall.com/lists/oss-security/2010/09/22/3
Reference: MLIST:[oss-security] 20100924 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases
Reference: URL:http://www.openwall.com/lists/oss-security/2010/09/24/3
Reference: MISC:http://bugs.python.org/issue6706
Reference: MISC:https://bugs.launchpad.net/zodb/+bug/135108
Reference: CONFIRM:http://bugs.python.org/issue9129
Reference: CONFIRM:http://svn.python.org/view/python/branches/py3k/Lib/smtpd.py?r1=84289&r2=84288&pathrev=84289
Reference: CONFIRM:http://svn.python.org/view?view=rev&revision=84289
Reference: CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=632200
Reference: MANDRIVA:MDVSA-2010:216
Reference: URL:http://www.mandriva.com/security/advisories?name=MDVSA-2010:216
Reference: MANDRIVA:MDVSA-2010:215
Reference: URL:http://www.mandriva.com/security/advisories?name=MDVSA-2010:215
Reference: SUSE:SUSE-SR:2010:024
Reference: URL:http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html
Reference: SUSE:SUSE-SR:2011:002
Reference: URL:http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html
Reference: UBUNTU:USN-1596-1
Reference: URL:http://www.ubuntu.com/usn/USN-1596-1
Reference: UBUNTU:USN-1613-2
Reference: URL:http://www.ubuntu.com/usn/USN-1613-2
Reference: UBUNTU:USN-1613-1
Reference: URL:http://www.ubuntu.com/usn/USN-1613-1
Reference: BID:44533
Reference: URL:http://www.securityfocus.com/bid/44533
Reference: OVAL:oval:org.mitre.oval:def:12210
Reference: URL:https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A12210
Reference: SECUNIA:43068
Reference: URL:http://secunia.com/advisories/43068
Reference: SECUNIA:50858
Reference: URL:http://secunia.com/advisories/50858
Reference: SECUNIA:51024
Reference: URL:http://secunia.com/advisories/51024
Reference: SECUNIA:51040
Reference: URL:http://secunia.com/advisories/51040
Reference: VUPEN:ADV-2011-0212
Reference: URL:http://www.vupen.com/english/advisories/2011/0212

Multiple race conditions in smtpd.py in the smtpd module in Python
2.6, 2.7, 3.1, and 3.2 alpha allow remote attackers to cause a denial
of service (daemon outage) by establishing and then immediately
closing a TCP connection, leading to the accept function having an
unexpected return value of None, an unexpected value of None for the
address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, or the
getpeername function having an ENOTCONN error, a related issue to
CVE-2010-3492.


Current Votes:
None (candidate not yet proposed)


