Name: CVE-2010-3495
Status: Candidate
URL: http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-3495
Phase: Assigned (20100924)
Category: 
Reference: MLIST:[oss-security] 20100909 CVE Request -- Python -- accept() implementation in async core is broken => more subcases
Reference: URL:http://www.openwall.com/lists/oss-security/2010/09/09/6
Reference: MLIST:[oss-security] 20100910 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases
Reference: URL:http://www.openwall.com/lists/oss-security/2010/09/11/2
Reference: MLIST:[oss-security] 20100922 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases
Reference: URL:http://www.openwall.com/lists/oss-security/2010/09/22/3
Reference: MLIST:[oss-security] 20100924 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases
Reference: URL:http://www.openwall.com/lists/oss-security/2010/09/24/3
Reference: MISC:http://bugs.python.org/issue6706
Reference: CONFIRM:http://pypi.python.org/pypi/ZODB3/3.10.0#id1
Reference: CONFIRM:https://bugs.launchpad.net/zodb/+bug/135108
Reference: SUSE:SUSE-SR:2010:024
Reference: URL:http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html
Reference: SECUNIA:41755
Reference: URL:http://secunia.com/advisories/41755

Race condition in ZEO/StorageServer.py in Zope Object Database (ZODB)
before 3.10.0 allows remote attackers to cause a denial of service
(daemon outage) by establishing and then immediately closing a TCP
connection, leading to the accept function having an unexpected return
value of None, an unexpected value of None for the address, or an
ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to
CVE-2010-3492.


Current Votes:
None (candidate not yet proposed)


